/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LectureController;
import Model.DatabaseConnection;
import Model.LectureModel;
import com.mycompany.university_ms.HomePage;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS Zenbook
 */
public class AddLecturesFrame extends javax.swing.JFrame {

    private LectureController lectureController;
    
    public AddLecturesFrame() {
        initComponents();
        Connection connection = DatabaseConnection.getConnection();
        lectureController = new LectureController(connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblClose1 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudentsDetails1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtLecturePhoneNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtLectureName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLectureEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSpealization = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbLectureDepartment = new javax.swing.JComboBox<>();
        btnClrLec = new javax.swing.JButton();
        btnUpdLec = new javax.swing.JButton();
        btnDelLec = new javax.swing.JButton();
        btnAddLec = new javax.swing.JButton();
        txtLectureId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose1.setBackground(new java.awt.Color(255, 255, 255));
        lblClose1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClose1.setText("X");
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
        });
        jPanel3.add(lblClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        btnBack2.setBackground(new java.awt.Color(153, 51, 255));
        btnBack2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("BACK");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 120, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\icons8-speech-64.png")); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Data of Lectures");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        tblStudentsDetails1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Lecture ID", "Name", "Email", "Phone No", "Department", "Specialization"
            }
        ));
        jScrollPane2.setViewportView(tblStudentsDetails1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 900, 290));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Lecture ID :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, -1));

        txtLecturePhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLecturePhoneNoActionPerformed(evt);
            }
        });
        jPanel3.add(txtLecturePhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 130, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Name :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 60, -1));

        txtLectureName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLectureNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtLectureName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 130, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Email :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 60, -1));

        txtLectureEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLectureEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txtLectureEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 190, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Phone No :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 90, -1));

        txtSpealization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpealizationActionPerformed(evt);
            }
        });
        jPanel3.add(txtSpealization, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Specialization :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Department :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 110, -1));

        cmbLectureDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Business", "School of Computing", "School of Language" }));
        jPanel3.add(cmbLectureDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 130, 30));

        btnClrLec.setBackground(new java.awt.Color(153, 51, 255));
        btnClrLec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClrLec.setForeground(new java.awt.Color(255, 255, 255));
        btnClrLec.setText("CLEAR");
        btnClrLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrLecActionPerformed(evt);
            }
        });
        jPanel3.add(btnClrLec, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 120, 30));

        btnUpdLec.setBackground(new java.awt.Color(153, 51, 255));
        btnUpdLec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdLec.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdLec.setText("UPDATE");
        btnUpdLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdLecActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdLec, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 120, 30));

        btnDelLec.setBackground(new java.awt.Color(153, 51, 255));
        btnDelLec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelLec.setForeground(new java.awt.Color(255, 255, 255));
        btnDelLec.setText("DELETE");
        btnDelLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLecActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelLec, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 120, 30));

        btnAddLec.setBackground(new java.awt.Color(153, 51, 255));
        btnAddLec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddLec.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLec.setText("ADD");
        btnAddLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLecActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddLec, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 120, 30));

        txtLectureId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLectureIdActionPerformed(evt);
            }
        });
        jPanel3.add(txtLectureId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 130, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 660));

        setSize(new java.awt.Dimension(941, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        int status  =  JOptionPane.showConfirmDialog(this,"Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if(status == JOptionPane.YES_OPTION){
            System.exit(status);
        }
    }//GEN-LAST:event_lblClose1MouseClicked

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed

        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        AddLecturesFrame.this.setVisible(false);

    }//GEN-LAST:event_btnBack2ActionPerformed

    private void txtLecturePhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLecturePhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLecturePhoneNoActionPerformed

    private void txtLectureNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLectureNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLectureNameActionPerformed

    private void txtLectureEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLectureEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLectureEmailActionPerformed

    private void txtSpealizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpealizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpealizationActionPerformed

    private void btnClrLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrLecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClrLecActionPerformed

    private void btnUpdLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdLecActionPerformed
        String lectureId = txtLectureId.getText();
        String name = txtLectureName.getText();
        String email = txtLectureEmail.getText();
        String phoneNo = txtLecturePhoneNo.getText();
        String department = cmbLectureDepartment.getSelectedItem().toString();
        String specialization = txtSpealization.getText();

        if (lectureId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lecture ID is required for updating.");
            return;
        }

        LectureModel lecture = new LectureModel(lectureId, name, email, phoneNo, department, specialization);

        if (lectureController.updateStudent(lecture)) {
            JOptionPane.showMessageDialog(null, "Lecture updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update lecture.");
        }
    }//GEN-LAST:event_btnUpdLecActionPerformed

    private void btnDelLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLecActionPerformed
        String lectureId = txtLectureId.getText();

        if (lectureId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lecture ID is required for deletion.");
            return;
        }

        if (lectureController.deleteLecture(lectureId)) {
            JOptionPane.showMessageDialog(null, "Lecture deleted successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to delete lecture.");
        }
    }//GEN-LAST:event_btnDelLecActionPerformed

    private void btnAddLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLecActionPerformed
        String lectureId = txtLectureId.getText();
        String name = txtLectureName.getText();
        String email = txtLectureEmail.getText();
        String phoneNo = txtLecturePhoneNo.getText();
        String department = cmbLectureDepartment.getSelectedItem().toString();
        String specialization = txtSpealization.getText();

        LectureModel lecture = new LectureModel(lectureId, name, email, phoneNo, department, specialization);

        if (lectureController.addLecture(lecture)) {
            JOptionPane.showMessageDialog(null, "Lecture added successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add lecture.");
        }
    }//GEN-LAST:event_btnAddLecActionPerformed

    private void txtLectureIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLectureIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLectureIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLecturesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLecturesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLecturesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLecturesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLecturesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLec;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnClrLec;
    private javax.swing.JButton btnDelLec;
    private javax.swing.JButton btnUpdLec;
    private javax.swing.JComboBox<String> cmbLectureDepartment;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JTable tblStudentsDetails1;
    private javax.swing.JTextField txtLectureEmail;
    private javax.swing.JTextField txtLectureId;
    private javax.swing.JTextField txtLectureName;
    private javax.swing.JTextField txtLecturePhoneNo;
    private javax.swing.JTextField txtSpealization;
    // End of variables declaration//GEN-END:variables
}
