/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DatabaseConnection;
import View.AddCoursesFrame;
import View.AddDepartmentFrame;
import View.AddLecturesFrame;
import View.AddStudentFrame;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.text.Document;

/**
 *
 * @author ASUS Zenbook
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        loadDashboardData();
    }
    
    
    private void loadDashboardData() {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/University",
                "root",
                "Anu200439"
        )) {
            // Query for student count
            String studentCountQuery = "SELECT COUNT(*) AS total_students FROM students";
            try (PreparedStatement ps = connection.prepareStatement(studentCountQuery)) {
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    lblAllStudents.setText("" + rs.getInt("total_students"));
                }
            }

            // Query for lecture count
            String lectureCountQuery = "SELECT COUNT(*) AS total_lectures FROM lectures";
            try (PreparedStatement ps = connection.prepareStatement(lectureCountQuery)) {
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    lblAllLectures.setText("" + rs.getInt("total_lectures"));
                }
            }

            // Query for total student payment
            String totalPaymentQuery = "SELECT SUM(payment) AS total_payment FROM students";
            try (PreparedStatement ps = connection.prepareStatement(totalPaymentQuery)) {
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    lblTotIncome.setText("Rs." + rs.getDouble("total_payment"));
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    public void refreshDashboard() {
        loadDashboardData();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddLectures = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        btnAddStudents = new javax.swing.JButton();
        btnAddDepartments = new javax.swing.JButton();
        btnAddCourses = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTotIncome = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblAllStudents = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblAllLectures = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Management System");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Are you want to Log Out?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        btnLogOut.setBackground(new java.awt.Color(153, 51, 255));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("University");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\Uni Icon.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 60, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 660));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddLectures.setBackground(new java.awt.Color(153, 51, 255));
        btnAddLectures.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddLectures.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLectures.setText("Add Lectures");
        btnAddLectures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLecturesActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddLectures, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 180, 60));

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        btnAddStudents.setBackground(new java.awt.Color(153, 51, 255));
        btnAddStudents.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudents.setText("Add Students");
        btnAddStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentsActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 180, 60));

        btnAddDepartments.setBackground(new java.awt.Color(153, 51, 255));
        btnAddDepartments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddDepartments.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDepartments.setText("Add Departments");
        btnAddDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentsActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, 60));

        btnAddCourses.setBackground(new java.awt.Color(153, 51, 255));
        btnAddCourses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourses.setText("Add Courses");
        btnAddCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCoursesActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 180, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\Courses.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 70, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\Lectures.png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 70, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\Department.png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\Students.png")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 70, 80));

        jPanel7.setBackground(new java.awt.Color(153, 51, 255));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(153, 51, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total of Uni Income");
        jPanel7.add(jLabel9);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\icons8-income-64.png")); // NOI18N
        jPanel7.add(jLabel12);

        lblTotIncome.setBackground(new java.awt.Color(153, 51, 255));
        lblTotIncome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotIncome.setForeground(new java.awt.Color(255, 255, 255));
        lblTotIncome.setText("0.00$");
        jPanel7.add(lblTotIncome);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 190, 120));

        jPanel8.setBackground(new java.awt.Color(153, 51, 255));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(153, 51, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total of Uni Students");
        jPanel8.add(jLabel10);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\All Students.png")); // NOI18N
        jPanel8.add(jLabel14);

        lblAllStudents.setBackground(new java.awt.Color(153, 51, 255));
        lblAllStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAllStudents.setForeground(new java.awt.Color(255, 255, 255));
        lblAllStudents.setText("0");
        jPanel8.add(lblAllStudents);

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 120));

        jPanel9.setBackground(new java.awt.Color(153, 51, 255));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(153, 51, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total of Uni Lectures");
        jPanel9.add(jLabel11);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS Zenbook\\Downloads\\icons8-speech-64.png")); // NOI18N
        jPanel9.add(jLabel16);

        lblAllLectures.setBackground(new java.awt.Color(153, 51, 255));
        lblAllLectures.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAllLectures.setForeground(new java.awt.Color(255, 255, 255));
        lblAllLectures.setText("0");
        jPanel9.add(lblAllLectures);

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 190, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 630, 660));

        setSize(new java.awt.Dimension(941, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int status  =  JOptionPane.showConfirmDialog(this,"Are you sure you want to Logout?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if(status == JOptionPane.YES_OPTION){
            LoginFrame logForm = new LoginFrame();
            logForm.setVisible(true);
            HomePage.this.setVisible(false);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int status  =  JOptionPane.showConfirmDialog(this,"Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if(status == JOptionPane.YES_OPTION){
            System.exit(status);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnAddDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentsActionPerformed
        AddDepartmentFrame depFrame = new  AddDepartmentFrame();
        depFrame.setVisible(true);
        HomePage.this.setVisible(false);
    }//GEN-LAST:event_btnAddDepartmentsActionPerformed

    private void btnAddStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentsActionPerformed
        AddStudentFrame studentFrame = new AddStudentFrame();
        studentFrame.setVisible(true);
        HomePage.this.setVisible(false);
    }//GEN-LAST:event_btnAddStudentsActionPerformed

    private void btnAddCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCoursesActionPerformed
        AddCoursesFrame courseFrame = new  AddCoursesFrame();
        courseFrame.setVisible(true);
        HomePage.this.setVisible(false);
    }//GEN-LAST:event_btnAddCoursesActionPerformed

    private void btnAddLecturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLecturesActionPerformed
        AddLecturesFrame lecFrame = new AddLecturesFrame();
        lecFrame.setVisible(true);
        HomePage.this.setVisible(false);
    }//GEN-LAST:event_btnAddLecturesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomePage().setVisible(true);
//            }
//        });

          SwingUtilities.invokeLater(() -> {
            HomePage app = new HomePage();
            app.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourses;
    private javax.swing.JButton btnAddDepartments;
    private javax.swing.JButton btnAddLectures;
    private javax.swing.JButton btnAddStudents;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAllLectures;
    private javax.swing.JLabel lblAllStudents;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblTotIncome;
    // End of variables declaration//GEN-END:variables
}
